
export interface Product {
	id: number;
	product_name: string;
	description: string;
	price: number;
	image: string;
	category: string;
	stock: number;
	feature: boolean;
	is_new: boolean;
	created_at?: string;
	updated_at?: string;
}

export const mockProducts: Product[] = [
	// Cameras
	{
		id: 1,
		product_name: "Canon EOS R6",
		description: "Full-frame mirrorless camera with 20MP sensor",
		price: 2499.99,
		image: "/assets/img/camera.jpg",
		category: "Cameras",
		stock: 10,
		feature: true,
		is_new: true,
		created_at: "2024-01-01",
		updated_at: "2024-01-01"
	},
	{
		id: 2,
		product_name: "Sony A7 IV",
		description: "33MP full-frame hybrid camera",
		price: 2699.99,
		image: "/assets/img/camera.jpg",
		category: "Cameras",
		stock: 8,
		feature: true,
		is_new: true,
	},
	{
		id: 3,
		product_name: "Nikon Z6 II",
		description: "24.5MP full-frame mirrorless camera",
		price: 1999.99,
		image: "/assets/img/camera.jpg",
		category: "Cameras",
		stock: 15,
		feature: false,
		is_new: false,
	},
	{
		id: 4,
		product_name: "Fujifilm X-T4",
		description: "26.1MP APS-C mirrorless camera",
		price: 1699.99,
		image: "/assets/img/camera.jpg",
		category: "Cameras",
		stock: 12,
		feature: false,
		is_new: false,
	},
	{
		id: 5,
		product_name: "Panasonic GH6",
		description: "25.2MP Micro Four Thirds camera",
		price: 2199.99,
		image: "/assets/img/camera.jpg",
		category: "Cameras",
		stock: 6,
		feature: true,
		is_new: false,
	},

	// Lenses
	{
		id: 6,
		product_name: "Canon RF 50mm f/1.2L",
		description: "Professional prime lens for RF mount",
		price: 2299.99,
		image: "/assets/img/camera.jpg",
		category: "Lenses",
		stock: 7,
		feature: true,
		is_new: true,
	},
	{
		id: 7,
		product_name: "Sony FE 24-70mm f/2.8 GM",
		description: "Professional zoom lens for E-mount",
		price: 2199.99,
		image: "/assets/img/camera.jpg",
		category: "Lenses",
		stock: 5,
		feature: true,
		is_new: false,
	},
	{
		id: 8,
		product_name: "Nikon Z 85mm f/1.8 S",
		description: "Portrait prime lens for Z-mount",
		price: 799.99,
		image: "/assets/img/camera.jpg",
		category: "Lenses",
		stock: 9,
		feature: false,
		is_new: true,
	},
	{
		id: 9,
		product_name: "Sigma 35mm f/1.4 Art",
		description: "Wide-angle prime lens",
		price: 899.99,
		image: "/assets/img/camera.jpg",
		category: "Lenses",
		stock: 11,
		feature: false,
		is_new: false,
	},
	{
		id: 10,
		product_name: "Tamron 70-200mm f/2.8",
		description: "Telephoto zoom lens",
		price: 1299.99,
		image: "/assets/img/camera.jpg",
		category: "Lenses",
		stock: 4,
		feature: true,
		is_new: false,
	},

	// Lighting
	{
		id: 11,
		product_name: "Profoto B10 Plus",
		description: "Professional studio flash",
		price: 2099.99,
		image: "/assets/img/camera.jpg",
		category: "Lighting",
		stock: 6,
		feature: true,
		is_new: true,
	},
	{
		id: 12,
		product_name: "Godox AD400Pro",
		description: "Portable strobe light",
		price: 649.99,
		image: "/assets/img/camera.jpg",
		category: "Lighting",
		stock: 8,
		feature: true,
		is_new: false,
	},
	{
		id: 13,
		product_name: "Aputure LS C300d III",
		description: "LED continuous light",
		price: 1099.99,
		image: "/assets/img/camera.jpg",
		category: "Lighting",
		stock: 5,
		feature: false,
		is_new: true,
	},
	{
		id: 14,
		product_name: "Nanlite Forza 60B",
		description: "Bi-color LED light",
		price: 399.99,
		image: "/assets/img/camera.jpg",
		category: "Lighting",
		stock: 12,
		feature: false,
		is_new: false,
	},
	{
		id: 15,
		product_name: "Westcott FJ400",
		description: "Portable strobe kit",
		price: 599.99,
		image: "/assets/img/camera.jpg",
		category: "Lighting",
		stock: 7,
		feature: true,
		is_new: false,
	},

	// Tripods & Supports
	{
		id: 16,
		product_name: "Really Right Stuff TFC-14 Series 1",
		description: "Carbon fiber tripod",
		price: 899.99,
		image: "/assets/img/camera.jpg",
		category: "Tripods & Supports",
		stock: 4,
		feature: true,
		is_new: true,
	},
	{
		id: 17,
		product_name: "Gitzo GT2542 Mountaineer",
		description: "Professional carbon fiber tripod",
		price: 999.99,
		image: "/assets/img/camera.jpg",
		category: "Tripods & Supports",
		stock: 6,
		feature: true,
		is_new: false,
	},
	{
		id: 18,
		product_name: "Manfrotto MT055XPRO4",
		description: "Aluminum tripod",
		price: 299.99,
		image: "/assets/img/camera.jpg",
		category: "Tripods & Supports",
		stock: 9,
		feature: false,
		is_new: false,
	},
	{
		id: 19,
		product_name: "Peak Design Travel Tripod",
		description: "Compact travel tripod",
		price: 599.99,
		image: "/assets/img/camera.jpg",
		category: "Tripods & Supports",
		stock: 7,
		feature: true,
		is_new: true,
	},
	{
		id: 20,
		product_name: "Benro Rhino FRHN34CVX30",
		description: "Video tripod kit",
		price: 699.99,
		image: "/assets/img/camera.jpg",
		category: "Tripods & Supports",
		stock: 5,
		feature: false,
		is_new: false,
	},

	// Accessories
	{
		id: 21,
		product_name: "Peak Design Everyday Backpack",
		description: "Camera backpack 30L",
		price: 299.99,
		image: "/assets/img/camera.jpg",
		category: "Accessories",
		stock: 15,
		feature: true,
		is_new: true,
	},
	{
		id: 22,
		product_name: "Lee Filters Foundation Kit",
		description: "Professional filter system",
		price: 199.99,
		image: "/assets/img/camera.jpg",
		category: "Accessories",
		stock: 8,
		feature: true,
		is_new: false,
	},
	{
		id: 23,
		product_name: "Rode VideoMic Pro+",
		description: "Shotgun microphone",
		price: 299.99,
		image: "/assets/img/camera.jpg",
		category: "Accessories",
		stock: 10,
		feature: false,
		is_new: true,
	},
	{
		id: 24,
		product_name: "SmallRig Camera Cage",
		description: "Universal camera cage",
		price: 149.99,
		image: "/assets/img/camera.jpg",
		category: "Accessories",
		stock: 12,
		feature: false,
		is_new: false,
	},
	{
		id: 25,
		product_name: "Atomos Ninja V",
		description: "5\" 4K HDR monitor-recorder",
		price: 649.99,
		image: "/assets/img/camera.jpg",
		category: "Accessories",
		stock: 6,
		feature: true,
		is_new: false,
	},

	// Studio Equipment
	{
		id: 26,
		product_name: "Savage Universal Paper Background",
		description: "9ft wide background roll",
		price: 69.99,
		image: "/assets/img/camera.jpg",
		category: "Studio Equipment",
		stock: 20,
		feature: true,
		is_new: false,
	},
	{
		id: 27,
		product_name: "Tether Tools Pro Tethering Kit",
		description: "Complete tethering solution",
		price: 199.99,
		image: "/assets/img/camera.jpg",
		category: "Studio Equipment",
		stock: 8,
		feature: true,
		is_new: true,
	},
	{
		id: 28,
		product_name: "C-Stand Kit",
		description: "Heavy duty light stand with boom arm",
		price: 149.99,
		image: "/assets/img/camera.jpg",
		category: "Studio Equipment",
		stock: 15,
		feature: false,
		is_new: false,
	},
	{
		id: 29,
		product_name: "Studio Desk Pro",
		description: "Photography workflow desk",
		price: 899.99,
		image: "/assets/img/camera.jpg",
		category: "Studio Equipment",
		stock: 4,
		feature: true,
		is_new: true,
	},
	{
		id: 30,
		product_name: "Impact Light Stand Kit",
		description: "Set of 3 light stands",
		price: 199.99,
		image: "/assets/img/camera.jpg",
		category: "Studio Equipment",
		stock: 7,
		feature: false,
		is_new: false,
	}
];